// ar slideIndex = 0;
// showSlides();
//
// function showSlides() {
//     var i;
//     var slides = document.getElementsByClassName("quote-container");
//     for (i = 0; i < slides.length; i++) {
//         slides[i].style.display = "none";
//     }
//     slideIndex++;
//     if (slideIndex > slides.length) {slideIndex = 1}
//     slides[slideIndex-1].style.display = "block";
//     setTimeout(showSlides, 2000); // Change image every 2 seconds
// }
//
//
//




// $(".quote-container").hide();
// setInterval(function() {
//   $('.testimonial-content> div:first')
//     .fadeOut(-1000)
//     .next()
//     .fadeIn(1000)
//     .end()
//     .appendTo('.testimonial-content');
// },  2000);
//
// $(".slick").slick({
//   infinite: true,
//   dots: true,
//   autoplay: true,
//   autoplaySpeed: 4000,
//   speed: 1000,
//   cssEase: "ease-in-out"
// });

// function nextIndex(div) {
//   let sliderIndex = 1;
//   let x =document.getElementsByClassName('quote-container');
//   let dots = document.getElementsByClassName('demo');
//   const testimonial = $('.testimonial-content');
//
//   for (x = 1; x < x.lenght, x ++){
//     x.next();
//   } if (x > x.lenght){
//     x === 1;
//   } for (i = 0; i < dots.length; i++) {
//      dots[i].className = dots[i].className.replace(" w3-white", "");
//   }
//   x[slideIndex-1].style.display = "block";
//   dots[slideIndex-1].className += " w3-white";
// }
//testimonial-content div hide
// $('.quote-container').hide();
//apper the first div quote-container //first div quote-container hide
// $('.testimonial-content > div')
// .first()
// .show()
// .fadeOut(-1000)
// .next()
// .fadeIn(1000)
// .end();
//show second quote-container div
// if it's the last div hide and show the first div
// if (testimonial === 0) {
//
// }
// if not continue to the second div quote-container
//appear with window load
